version: '3.8'

services:
  discriminate_ea_embedding_service:
    image:  sinequa:5000/discriminate_ea:0.1.0
    container_name: discriminate_ea_embedding_service

    cpuset: ${CPU_IDS}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      HF_HOME: "/tmp/hf_cache"
      HF_TOKEN: "${HF_TOKEN}"
      DATASET: "${DATASET}" 

    user: "${USER_UID}:${USER_GID}"  # Define USER_UID and USER_GID in .env file

    group_add:
      - "${DOCKER_GID}"  # Define DOCKER_GID in .env file

    working_dir: /workspace

    volumes:
      - /raid/ml-data/paco/discriminate_ea_data:/workspace/data
      - /home/paco/projects/discriminateEA/trained_models:/workspace/trained_models
      - /home/paco/projects/discriminateEA/results:/workspace/results
      - /tmp/hf_cache_${USER_UID}:/tmp/hf_cache

    command:
      [
        "python", "-m", "discriminate_ea.produce_embedding",
        "--dataset", "${DATASET}"
      ]